export const ActionTypes = {
  IS_FETCHING_DATA: "IS_FETCHING_DATA",
  SET_BAD_REQUEST: "SET_BAD_REQUEST",
  NO_INTERNET: "NO_INTERNET",
  SET_CURRENT_BOOKS: "SET_CURRENT_BOOKS",
  SET_SINGLE_BOOK: "SET_SINGLE_BOOK",
  SET_FEATURED_BOOKS: "SET_FEATURED_BOOKS",
  SET_BEST_OFFER_BOOKS: "SET_BEST_OFFER_BOOKS",
  SET_USER_IS_AUTHENTICATED: "SET_USER_IS_AUTHENTICATED",
  SET_USER_INFO: "SET_USER_INFO",
  REMOVE_USER_INFO: "REMOVE_USER_INFO",
  SET_DASHBOARD_INFO: "SET_DASHBOARD_INFO",
};
