import img1 from "./static/products/product-item1.jpg";
import img2 from "./static/products/product-item2.jpg";
import img3 from "./static/products/product-item3.jpg";
import img4 from "./static/products/product-item4.jpg";
import img5 from "./static/products/product-item5.jpg";
import img6 from "./static/products/product-item6.jpg";
import img7 from "./static/products/product-item7.jpg";
import img8 from "./static/products/product-item8.jpg";
import img9 from "./static/products/product-item9.jpg";
import img10 from "./static/products/single-image.jpg";
import img11 from "./static/products/tab-item1.jpg";
import img12 from "./static/products/tab-item3.jpg";
import img13 from "./static/products/tab-item4.jpg";
import img14 from "./static/products/tab-item5.jpg";
import img15 from "./static/products/tab-item7.jpg";

import cat1 from "./static/cat1.png";
import cat2 from "./static/cat2.png";
import cat3 from "./static/cat3.png";
import cat4 from "./static/cat4.png";
import cat5 from "./static/cat5.png";
import cat6 from "./static/cat6.png";

export const quotes = [
  {
    quote:
      "Reading is essential for those who seek to rise above the ordinary.",
    author: "Jim Rohn",
  },
  {
    quote: "Think before you speak. Read before you think.",
    author: "Fran Lebowitz",
  },
  {
    quote: "A room without books is like a body without a soul.",
    author: "Cicero",
  },
  {
    quote: "A book is a gift you can open again and again.",
    author: "Garrison Keillor",
  },
];

export const allProducts = [
  {
    key: "/works/OL7938488W",
    title: "Molecular Biology of the Cell",
    edition_count: 34,
    cover_id: 1547643,
    cover_edition_key: "OL9657854M",
    subject: [
      "biology",
      "cells",
      "cell biology",
      "textbook",
      "nonfiction",
      "reference work",
      "Amino Acids",
      "Cytology",
      "Molecular biology",
      "Molecular Biology",
      "Cells",
      "Neoplasms",
      "Cell Membrane",
      "Stem Cells",
      "DNA",
      "Cell Communication",
      "Microbiology",
      "Zelle",
      "Moleculaire biologie",
      "Molekularbiologie",
      "Celbiologie",
      "Moleküler Biyoloji",
      "Cellules",
      "Biologie moléculaire",
      "Sitoloji",
      "Cells.\u001e 2",
      "42.15 cytology, cell biology and cell physiology",
      "Citologia",
      "Biologia celular",
      "Biologia molecular",
      "Cytologie",
      "42.13 molecular biology",
      "Long Now Manual for Civilization",
      "Citologi a.",
      "Biologi a molecular",
      "Citologi a",
      "Science",
      "Cell physiology",
      "Cell Biology",
    ],
    ia_collection: [
      "americanuniversity-ol",
      "binghamton-ol",
      "china",
      "cua-ol",
      "dartmouthlibrary-ol",
      "gwulibraries-ol",
      "inlibrary",
      "internetarchivebooks",
      "johnshopkins-ol",
      "librarygenesis",
      "marymount-ol",
      "occidentalcollegelibrary-ol",
      "openlibrary-d-ol",
      "printdisabled",
      "rochester-ol",
      "smithsonianlibraries",
      "the-claremont-colleges-ol",
      "tulsacc-ol",
      "udc-ol",
      "uhmauicollege-ol",
      "unb-ol",
      "uni-ol",
      "universityofarizona-ol",
      "universityofcoloradoboulder-ol",
      "universityofoklahoma-ol",
      "universityofthewest-ol",
      "wilsoncollege-ol",
    ],
    lendinglibrary: false,
    printdisabled: true,
    lending_edition: "OL3495682M",
    lending_identifier: "molecularbiology0000unse_e2q3",
    authors: [
      {
        key: "/authors/OL2646473A",
        name: "Bruce Alberts",
      },
      {
        key: "/authors/OL2848659A",
        name: "Alexander Johnson",
      },
      {
        key: "/authors/OL7466358A",
        name: "Julian Lewis",
      },
      {
        key: "/authors/OL2640982A",
        name: "David Morgan",
      },
      {
        key: "/authors/OL2848471A",
        name: "Martin Raff",
      },
      {
        key: "/authors/OL977170A",
        name: "Julian Lewis",
      },
      {
        key: "/authors/OL2643381A",
        name: "Keith Roberts",
      },
      {
        key: "/authors/OL2848660A",
        name: "Peter Walter",
      },
      {
        key: "/authors/OL7555968A",
        name: "Alexander D. Johnson",
      },
      {
        key: "/authors/OL3011644A",
        name: "Alberts",
      },
      {
        key: "/authors/OL3265651A",
        name: "Alberts Et Al.",
      },
    ],
    first_publish_year: 1983,
    ia: "molecularbiology0000unse_e2q3",
    public_scan: false,
    has_fulltext: true,
    availability: {
      status: "borrow_available",
      available_to_browse: true,
      available_to_borrow: true,
      available_to_waitlist: false,
      is_printdisabled: true,
      is_readable: false,
      is_lendable: true,
      is_previewable: true,
      identifier: "molecularbiology0000unse_e2q3",
      isbn: "0824072820",
      oclc: null,
      openlibrary_work: "OL19578125W",
      openlibrary_edition: "OL3495682M",
      last_loan_date: null,
      num_waitlist: null,
      last_waitlist_date: null,
      is_restricted: true,
      is_browseable: true,
      __src__: "core.models.lending.get_availability",
    },
  },
  {
    key: "/works/OL3666701W",
    title: "Ukraine",
    edition_count: 16,
    cover_id: 568114,
    cover_edition_key: "OL7873916M",
    subject: ["History", "Histoire", "Ukraine", "Textbook", "Ukraine, history"],
    ia_collection: [
      "binghamton-ol",
      "china",
      "dartmouthlibrary-ol",
      "gwulibraries-ol",
      "inlibrary",
      "internetarchivebooks",
      "johnshopkins-ol",
      "printdisabled",
      "the-claremont-colleges-ol",
      "universityofarizona-ol",
      "universityofcoloradoboulder-ol",
      "universityofoklahoma-ol",
    ],
    lendinglibrary: false,
    printdisabled: true,
    lending_edition: "OL26418731M",
    lending_identifier: "ukrainehistory00subt_0",
    authors: [{ key: "/authors/OL630987A", name: "Orest Subtelny" }],
    first_publish_year: 1988,
    ia: "ukrainehistory00subt_0",
    public_scan: false,
    has_fulltext: true,
    availability: {
      status: "borrow_available",
      available_to_browse: true,
      available_to_borrow: true,
      available_to_waitlist: false,
      is_printdisabled: true,
      is_readable: false,
      is_lendable: true,
      is_previewable: true,
      identifier: "ukrainehistory00subt_0",
      isbn: "0802083900",
      oclc: null,
      openlibrary_work: "OL3666701W",
      openlibrary_edition: "OL3963771M",
      last_loan_date: "2020-05-27T02:55:11Z",
      num_waitlist: "0",
      last_waitlist_date: "2019-04-18T12:47:25Z",
      is_restricted: true,
      is_browseable: true,
      __src__: "core.models.lending.get_availability",
    },
  },
];

export const justBooks = [
  {
    name: "Once Upon A Time",
    slug: "once-upon-a-time",
    image: img8,
    author: "Klien Marry",
    price: "35.00",
  },
  {
    name: "Does To Me",
    slug: "once-upon-a-time",
    image: img7,
    author: "Orlando Owoh",
    price: "25.00",
  },
];

export const justHistory = [
  {
    name: "Simple Way Of Piece Life",
    slug: "simple-way-of-piece-life",
    image: img1,
    author: "Armor Ramsey",
    price: "40.00",
  },
  {
    name: "Great Travel At Desert",
    slug: "great-travel-at-desert",
    image: img2,
    author: "Sanchit Howdy",
    price: "38.00",
  },
];

export const allCategoryList = [
  {
    name: "Textbooks",
    image: cat1,
  },
  {
    name: "Programming",
    image: cat2,
  },
  {
    name: "History",
    image: cat3,
  },
  {
    name: "Biography",
    image: cat4,
  },
  {
    name: "Adventure",
    image: cat5,
  },
  {
    name: "Fantasy",
    image: cat6,
  },
];

export const allImages = [img1, img5, img6, img9, img10, img11];

let subjects = {
  key: "/works/OL7938488W",
  title: "Molecular Biology of the Cell",
  edition_count: 34,
  cover_id: 1547643,
  cover_edition_key: "OL9657854M",
  subject: [
    "biology",
    "cells",
    "cell biology",
    "textbook",
    "nonfiction",
    "reference work",
    "Amino Acids",
    "Cytology",
    "Molecular biology",
    "Molecular Biology",
    "Cells",
    "Neoplasms",
    "Cell Membrane",
    "Stem Cells",
    "DNA",
    "Cell Communication",
    "Microbiology",
    "Zelle",
    "Moleculaire biologie",
    "Molekularbiologie",
    "Celbiologie",
    "Moleküler Biyoloji",
    "Cellules",
    "Biologie moléculaire",
    "Sitoloji",
    "Cells.\u001e 2",
    "42.15 cytology, cell biology and cell physiology",
    "Citologia",
    "Biologia celular",
    "Biologia molecular",
    "Cytologie",
    "42.13 molecular biology",
    "Long Now Manual for Civilization",
    "Citologi a.",
    "Biologi a molecular",
    "Citologi a",
    "Science",
    "Cell physiology",
    "Cell Biology",
  ],
  ia_collection: [
    "americanuniversity-ol",
    "binghamton-ol",
    "china",
    "cua-ol",
    "dartmouthlibrary-ol",
    "gwulibraries-ol",
    "inlibrary",
    "internetarchivebooks",
    "johnshopkins-ol",
    "librarygenesis",
    "marymount-ol",
    "occidentalcollegelibrary-ol",
    "openlibrary-d-ol",
    "printdisabled",
    "rochester-ol",
    "smithsonianlibraries",
    "the-claremont-colleges-ol",
    "tulsacc-ol",
    "udc-ol",
    "uhmauicollege-ol",
    "unb-ol",
    "uni-ol",
    "universityofarizona-ol",
    "universityofcoloradoboulder-ol",
    "universityofoklahoma-ol",
    "universityofthewest-ol",
    "wilsoncollege-ol",
  ],
  lendinglibrary: false,
  printdisabled: true,
  lending_edition: "OL3495682M",
  lending_identifier: "molecularbiology0000unse_e2q3",
  authors: [
    {
      key: "/authors/OL2646473A",
      name: "Bruce Alberts",
    },
    {
      key: "/authors/OL2848659A",
      name: "Alexander Johnson",
    },
    {
      key: "/authors/OL7466358A",
      name: "Julian Lewis",
    },
    {
      key: "/authors/OL2640982A",
      name: "David Morgan",
    },
    {
      key: "/authors/OL2848471A",
      name: "Martin Raff",
    },
    {
      key: "/authors/OL977170A",
      name: "Julian Lewis",
    },
    {
      key: "/authors/OL2643381A",
      name: "Keith Roberts",
    },
    {
      key: "/authors/OL2848660A",
      name: "Peter Walter",
    },
    {
      key: "/authors/OL7555968A",
      name: "Alexander D. Johnson",
    },
    {
      key: "/authors/OL3011644A",
      name: "Alberts",
    },
    {
      key: "/authors/OL3265651A",
      name: "Alberts Et Al.",
    },
  ],
  first_publish_year: 1983,
  ia: "molecularbiology0000unse_e2q3",
  public_scan: false,
  has_fulltext: true,
  availability: {
    status: "borrow_available",
    available_to_browse: true,
    available_to_borrow: true,
    available_to_waitlist: false,
    is_printdisabled: true,
    is_readable: false,
    is_lendable: true,
    is_previewable: true,
    identifier: "molecularbiology0000unse_e2q3",
    isbn: "0824072820",
    oclc: null,
    openlibrary_work: "OL19578125W",
    openlibrary_edition: "OL3495682M",
    last_loan_date: null,
    num_waitlist: null,
    last_waitlist_date: null,
    is_restricted: true,
    is_browseable: true,
    __src__: "core.models.lending.get_availability",
  },
};

let searchTins = [
  {
    key: "/works/OL21519279W",
    type: "work",
    seed: [
      "/books/OL29182449M",
      "/books/OL29650409M",
      "/works/OL21519279W",
      "/subjects/fiction_suspense",
      "/subjects/fiction_thrillers_general",
      "/subjects/criminals",
      "/subjects/assassins",
      "/subjects/fiction",
      "/subjects/fiction_thrillers_espionage",
      "/subjects/fiction_thrillers_suspense",
      "/authors/OL33236A",
    ],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 2,
    edition_key: ["OL29182449M", "OL29650409M"],
    publish_date: ["2012"],
    publish_year: [2012],
    first_publish_year: 2012,
    number_of_pages_median: 275,
    lccn: ["2014656421"],
    isbn: ["9780345471345", "9780755397372", "0755397371", "0345471342"],
    last_modified_i: 1673788392,
    ebook_count_i: 1,
    ebook_access: "borrowable",
    has_fulltext: true,
    public_scan_b: false,
    ia: ["hitmandamnation0000bens"],
    ia_collection: [
      "hamiltonpubliclibrary-ol",
      "inlibrary",
      "internetarchivebooks",
      "openlibrary-d-ol",
      "printdisabled",
    ],
    ia_collection_s:
      "hamiltonpubliclibrary-ol;inlibrary;internetarchivebooks;openlibrary-d-ol;printdisabled",
    lending_edition_s: "OL29650409M",
    lending_identifier_s: "hitmandamnation0000bens",
    printdisabled_s: "OL29650409M",
    readinglog_count: 2,
    want_to_read_count: 2,
    currently_reading_count: 0,
    already_read_count: 0,
    cover_edition_key: "OL29650409M",
    cover_i: 11645427,
    publisher: ["Random House Publishing Group", "Headline Publishing Group"],
    language: ["eng"],
    author_key: ["OL33236A"],
    author_name: ["Raymond Benson"],
    author_alternative_name: ["Raymond Benson."],
    subject: [
      "Fiction, suspense",
      "Fiction, thrillers, general",
      "Criminals",
      "Assassins",
      "Fiction",
      "Fiction, thrillers, espionage",
      "Fiction, thrillers, suspense",
    ],
    ia_box_id: ["IA1990620"],
    publisher_facet: [
      "Headline Publishing Group",
      "Random House Publishing Group",
    ],
    subject_facet: [
      "Assassins",
      "Criminals",
      "Fiction",
      "Fiction, suspense",
      "Fiction, thrillers, espionage",
      "Fiction, thrillers, general",
      "Fiction, thrillers, suspense",
    ],
    _version_: 1759764772421632000,
    author_facet: ["OL33236A Raymond Benson"],
    subject_key: [
      "assassins",
      "criminals",
      "fiction",
      "fiction_suspense",
      "fiction_thrillers_espionage",
      "fiction_thrillers_general",
      "fiction_thrillers_suspense",
    ],
  },
  {
    key: "/works/OL28033356W",
    type: "work",
    seed: [
      "/books/OL38354973M",
      "/works/OL28033356W",
      "/subjects/fiction_thrillers_suspense",
      "/subjects/fiction_thrillers_general",
      "/authors/OL6789122A",
    ],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 1,
    edition_key: ["OL38354973M"],
    publish_date: ["2012"],
    publish_year: [2012],
    first_publish_year: 2012,
    isbn: ["9780345535856", "0345535855"],
    last_modified_i: 1655546698,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Random House Publishing Group"],
    language: ["eng"],
    author_key: ["OL6789122A"],
    author_name: ["Raymond Benson"],
    subject: ["Fiction, thrillers, suspense", "Fiction, thrillers, general"],
    publisher_facet: ["Random House Publishing Group"],
    subject_facet: [
      "Fiction, thrillers, general",
      "Fiction, thrillers, suspense",
    ],
    _version_: 1759777170896453600,
    author_facet: ["OL6789122A Raymond Benson"],
    subject_key: ["fiction_thrillers_general", "fiction_thrillers_suspense"],
  },
];
