import img1 from "./static/products/product-item1.jpg";
import img2 from "./static/products/product-item2.jpg";
import img3 from "./static/products/product-item3.jpg";
import img4 from "./static/products/product-item4.jpg";
import img5 from "./static/products/product-item5.jpg";
import img6 from "./static/products/product-item6.jpg";
import img7 from "./static/products/product-item7.jpg";
import img8 from "./static/products/product-item8.jpg";
import img9 from "./static/products/product-item9.jpg";
import img10 from "./static/products/single-image.jpg";
import img11 from "./static/products/tab-item1.jpg";
import img12 from "./static/products/tab-item3.jpg";
import img13 from "./static/products/tab-item4.jpg";
import img14 from "./static/products/tab-item5.jpg";
import img15 from "./static/products/tab-item7.jpg";

import cat1 from "./static/cat1.png";
import cat2 from "./static/cat2.png";
import cat3 from "./static/cat3.png";
import cat4 from "./static/cat4.png";
import cat5 from "./static/cat5.png";
import cat6 from "./static/cat6.png";

export const quotes = [
  {
    quote:
      "Reading is essential for those who seek to rise above the ordinary.",
    author: "Jim Rohn",
  },
  {
    quote: "Think before you speak. Read before you think.",
    author: "Fran Lebowitz",
  },
  {
    quote: "A room without books is like a body without a soul.",
    author: "Cicero",
  },
  {
    quote: "A book is a gift you can open again and again.",
    author: "Garrison Keillor",
  },
];

export const allProducts = [
  {
    key: "/works/OL7938488W",
    title: "Molecular Biology of the Cell",
    edition_count: 34,
    cover_id: 1547643,
    cover_edition_key: "OL9657854M",
    subject: [
      "biology",
      "cells",
      "cell biology",
      "textbook",
      "nonfiction",
      "reference work",
      "Amino Acids",
      "Cytology",
      "Molecular biology",
      "Molecular Biology",
      "Cells",
      "Neoplasms",
      "Cell Membrane",
      "Stem Cells",
      "DNA",
      "Cell Communication",
      "Microbiology",
      "Zelle",
      "Moleculaire biologie",
      "Molekularbiologie",
      "Celbiologie",
      "Moleküler Biyoloji",
      "Cellules",
      "Biologie moléculaire",
      "Sitoloji",
      "Cells.\u001e 2",
      "42.15 cytology, cell biology and cell physiology",
      "Citologia",
      "Biologia celular",
      "Biologia molecular",
      "Cytologie",
      "42.13 molecular biology",
      "Long Now Manual for Civilization",
      "Citologi a.",
      "Biologi a molecular",
      "Citologi a",
      "Science",
      "Cell physiology",
      "Cell Biology",
    ],
    ia_collection: [
      "americanuniversity-ol",
      "binghamton-ol",
      "china",
      "cua-ol",
      "dartmouthlibrary-ol",
      "gwulibraries-ol",
      "inlibrary",
      "internetarchivebooks",
      "johnshopkins-ol",
      "librarygenesis",
      "marymount-ol",
      "occidentalcollegelibrary-ol",
      "openlibrary-d-ol",
      "printdisabled",
      "rochester-ol",
      "smithsonianlibraries",
      "the-claremont-colleges-ol",
      "tulsacc-ol",
      "udc-ol",
      "uhmauicollege-ol",
      "unb-ol",
      "uni-ol",
      "universityofarizona-ol",
      "universityofcoloradoboulder-ol",
      "universityofoklahoma-ol",
      "universityofthewest-ol",
      "wilsoncollege-ol",
    ],
    lendinglibrary: false,
    printdisabled: true,
    lending_edition: "OL3495682M",
    lending_identifier: "molecularbiology0000unse_e2q3",
    authors: [
      {
        key: "/authors/OL2646473A",
        name: "Bruce Alberts",
      },
      {
        key: "/authors/OL2848659A",
        name: "Alexander Johnson",
      },
      {
        key: "/authors/OL7466358A",
        name: "Julian Lewis",
      },
      {
        key: "/authors/OL2640982A",
        name: "David Morgan",
      },
      {
        key: "/authors/OL2848471A",
        name: "Martin Raff",
      },
      {
        key: "/authors/OL977170A",
        name: "Julian Lewis",
      },
      {
        key: "/authors/OL2643381A",
        name: "Keith Roberts",
      },
      {
        key: "/authors/OL2848660A",
        name: "Peter Walter",
      },
      {
        key: "/authors/OL7555968A",
        name: "Alexander D. Johnson",
      },
      {
        key: "/authors/OL3011644A",
        name: "Alberts",
      },
      {
        key: "/authors/OL3265651A",
        name: "Alberts Et Al.",
      },
    ],
    first_publish_year: 1983,
    ia: "molecularbiology0000unse_e2q3",
    public_scan: false,
    has_fulltext: true,
    availability: {
      status: "borrow_available",
      available_to_browse: true,
      available_to_borrow: true,
      available_to_waitlist: false,
      is_printdisabled: true,
      is_readable: false,
      is_lendable: true,
      is_previewable: true,
      identifier: "molecularbiology0000unse_e2q3",
      isbn: "0824072820",
      oclc: null,
      openlibrary_work: "OL19578125W",
      openlibrary_edition: "OL3495682M",
      last_loan_date: null,
      num_waitlist: null,
      last_waitlist_date: null,
      is_restricted: true,
      is_browseable: true,
      __src__: "core.models.lending.get_availability",
    },
  },
  {
    key: "/works/OL3666701W",
    title: "Ukraine",
    edition_count: 16,
    cover_id: 568114,
    cover_edition_key: "OL7873916M",
    subject: ["History", "Histoire", "Ukraine", "Textbook", "Ukraine, history"],
    ia_collection: [
      "binghamton-ol",
      "china",
      "dartmouthlibrary-ol",
      "gwulibraries-ol",
      "inlibrary",
      "internetarchivebooks",
      "johnshopkins-ol",
      "printdisabled",
      "the-claremont-colleges-ol",
      "universityofarizona-ol",
      "universityofcoloradoboulder-ol",
      "universityofoklahoma-ol",
    ],
    lendinglibrary: false,
    printdisabled: true,
    lending_edition: "OL26418731M",
    lending_identifier: "ukrainehistory00subt_0",
    authors: [{ key: "/authors/OL630987A", name: "Orest Subtelny" }],
    first_publish_year: 1988,
    ia: "ukrainehistory00subt_0",
    public_scan: false,
    has_fulltext: true,
    availability: {
      status: "borrow_available",
      available_to_browse: true,
      available_to_borrow: true,
      available_to_waitlist: false,
      is_printdisabled: true,
      is_readable: false,
      is_lendable: true,
      is_previewable: true,
      identifier: "ukrainehistory00subt_0",
      isbn: "0802083900",
      oclc: null,
      openlibrary_work: "OL3666701W",
      openlibrary_edition: "OL3963771M",
      last_loan_date: "2020-05-27T02:55:11Z",
      num_waitlist: "0",
      last_waitlist_date: "2019-04-18T12:47:25Z",
      is_restricted: true,
      is_browseable: true,
      __src__: "core.models.lending.get_availability",
    },
  },
];

export const justBooks = [
  {
    name: "Once Upon A Time",
    slug: "once-upon-a-time",
    image: img8,
    author: "Klien Marry",
    price: "35.00",
  },
  {
    name: "Does To Me",
    slug: "once-upon-a-time",
    image: img7,
    author: "Orlando Owoh",
    price: "25.00",
  },
];

export const justHistory = [
  {
    name: "Simple Way Of Piece Life",
    slug: "simple-way-of-piece-life",
    image: img1,
    author: "Armor Ramsey",
    price: "40.00",
  },
  {
    name: "Great Travel At Desert",
    slug: "great-travel-at-desert",
    image: img2,
    author: "Sanchit Howdy",
    price: "38.00",
  },
];

export const allCategoryList = [
  {
    name: "Textbooks",
    image: cat1,
  },
  {
    name: "Programming",
    image: cat2,
  },
  {
    name: "Mystery",
    image: cat3,
  },
  {
    name: "Horror",
    image: cat4,
  },
  {
    name: "Adventure",
    image: cat5,
  },
  {
    name: "Thriller",
    image: cat6,
  },
];

export const allImages = [img1, img5, img6, img9, img10, img11];

export const subjects = [
  {
    key: "/works/OL78065W",
    title: "The sea lions",
    edition_count: 51,
    cover_id: 2949613,
    cover_edition_key: "OL12366413M",
    subject: [
      "Sealers (Persons)",
      "Fiction",
      "American Sea stories",
      "Historical fiction",
      "Classic Literature",
      "Thriller",
      "Fiction, historical, general",
      "American literature",
      "American fiction (fictional works by one author)",
    ],
    ia_collection: [
      "americana",
      "cdl",
      "library_of_congress",
      "robarts",
      "toronto",
    ],
    lendinglibrary: false,
    printdisabled: false,
    lending_edition: "OL7242004M",
    lending_identifier: "selionsorlostsea00cooprich",
    authors: [{ key: "/authors/OL39524A", name: "James Fenimore Cooper" }],
    first_publish_year: 1800,
    ia: "selionsorlostsea00cooprich",
    public_scan: true,
    has_fulltext: true,
    availability: {
      status: "open",
      available_to_browse: false,
      available_to_borrow: false,
      available_to_waitlist: false,
      is_printdisabled: false,
      is_readable: true,
      is_lendable: false,
      is_previewable: true,
      identifier: "selionsorlostsea00cooprich",
      isbn: null,
      oclc: null,
      openlibrary_work: "OL78065W",
      openlibrary_edition: "OL7242004M",
      last_loan_date: null,
      num_waitlist: null,
      last_waitlist_date: null,
      is_restricted: false,
      is_browseable: false,
      __src__: "core.models.lending.get_availability",
    },
  },
  {
    key: "/works/OL41254W",
    title: "Last Man Standing",
    edition_count: 51,
    cover_id: 9158779,
    cover_edition_key: "OL20932616M",
    subject: [
      "Federal Bureau of Investigation",
      "Open Library Staff Picks",
      "Government investigators",
      "Fiction",
      "Federal Bureau of Investigation. Hostage Rescue Team",
      "Thriller",
      "Fiction, thrillers, general",
      "Fiction, espionage",
      "Large type books",
      "Fiction, suspense",
      "Fiction, thrillers",
      "Fiction, mystery & detective, police procedural",
      "Hostage Rescue team",
      "United States. Federal Bureau of Investigation. Hostage Rescue Team",
      "United States",
      "Fiction, thrillers, espionage",
      "Fiction, general",
      "Fiction, mystery & detective, general",
    ],
    ia_collection: [
      "americana",
      "china",
      "delawarecountydistrictlibrary",
      "inlibrary",
      "internetarchivebooks",
      "openlibrary-d-ol",
      "printdisabled",
    ],
    lendinglibrary: false,
    printdisabled: true,
    lending_edition: "OL28347905M",
    lending_identifier: "lastmanstanding0000bald",
    authors: [
      { key: "/authors/OL28165A", name: "David Baldacci" },
      { key: "/authors/OL1391499A", name: "Ron McLarty" },
      { key: "/authors/OL7853814A", name: "Jason Culp" },
    ],
    first_publish_year: 2001,
    ia: "lastmanstanding0000bald",
    public_scan: false,
    has_fulltext: true,
    availability: {
      status: "borrow_available",
      available_to_browse: true,
      available_to_borrow: true,
      available_to_waitlist: false,
      is_printdisabled: true,
      is_readable: false,
      is_lendable: true,
      is_previewable: true,
      identifier: "lastmanstanding0000bald",
      isbn: "0330518488",
      oclc: null,
      openlibrary_work: "OL41254W",
      openlibrary_edition: "OL28347905M",
      last_loan_date: null,
      num_waitlist: null,
      last_waitlist_date: null,
      is_restricted: true,
      is_browseable: true,
      __src__: "core.models.lending.get_availability",
    },
  },
  {
    key: "/works/OL1701007W",
    title: "Learning Perl",
    edition_count: 24,
    cover_id: 805582,
    cover_edition_key: "OL1204776M",
    subject: [
      "Perl (Computer program language)",
      "Perl (Computer utility)",
      "UNIX (Computer file)",
      "Utilities (Computer programs)",
      "PERL",
      "Perl (programspr\u00e5k)",
      "Perl (Langage de programmation)",
      "COMPUTERS",
      "Programming Languages",
      "Perl",
      "Perl (langage de programmation)",
      "Programmation PERL",
    ],
    ia_collection: [
      "americana",
      "china",
      "gwulibraries-ol",
      "inlibrary",
      "internetarchivebooks",
      "johnshopkins-ol",
      "librarygenesis",
      "printdisabled",
      "unb-ol",
    ],
    lendinglibrary: false,
    printdisabled: true,
    lending_edition: "OL1204776M",
    lending_identifier: "learningperl000schw",
    authors: [
      { key: "/authors/OL193717A", name: "Randal L. Schwartz" },
      { key: "/authors/OL2726794A", name: "Tom Phoenix" },
      { key: "/authors/OL2727034A", name: "brian d foy" },
    ],
    first_publish_year: 1993,
    ia: "learningperl000schw",
    public_scan: false,
    has_fulltext: true,
    availability: {
      status: "borrow_available",
      available_to_browse: true,
      available_to_borrow: false,
      available_to_waitlist: false,
      is_printdisabled: true,
      is_readable: false,
      is_lendable: true,
      is_previewable: true,
      identifier: "learningperl000schw",
      isbn: "9781565920422",
      oclc: null,
      openlibrary_work: "OL1701007W",
      openlibrary_edition: "OL1204776M",
      last_loan_date: "2020-05-25T22:56:23Z",
      num_waitlist: "0",
      last_waitlist_date: "2018-12-29T04:54:14Z",
      is_restricted: true,
      is_browseable: true,
      __src__: "core.models.lending.get_availability",
    },
  },
  {
    key: "/works/OL2784125W",
    title: "Learning Python",
    edition_count: 20,
    cover_id: 1312568,
    cover_edition_key: "OL9497269M",
    subject: [
      "Python (Langage de programmation)",
      "Python (linguagem de programa\u00e7\u00e3o)",
      "Python (Computer program language)",
      "Python (Lenguaje de programaci\u00f3n de computadores)",
      "Langage \u00e0 objets",
      "Python (programmeertaal)",
      "Object-oriented programming (Computer science)",
      "Python (Computer language)",
      "Interpr\u00e9teur",
      "Python",
      "COMPUTERS",
      "Programming Languages",
      "Engineering & Applied Sciences",
      "Computer Science",
    ],
    ia_collection: [
      "americana",
      "inlibrary",
      "internetarchivebooks",
      "librarygenesis",
      "printdisabled",
      "schroederlibrary-ol",
    ],
    lendinglibrary: false,
    printdisabled: true,
    lending_edition: "OL6804857M",
    lending_identifier: "learningpython00lutz",
    authors: [
      { key: "/authors/OL411267A", name: "Mark Lutz" },
      { key: "/authors/OL2726848A", name: "David Ascher" },
    ],
    first_publish_year: 1999,
    ia: "learningpython00lutz",
    public_scan: false,
    has_fulltext: true,
    availability: {
      status: "borrow_available",
      available_to_browse: true,
      available_to_borrow: false,
      available_to_waitlist: false,
      is_printdisabled: true,
      is_readable: false,
      is_lendable: true,
      is_previewable: true,
      identifier: "learningpython00lutz",
      // isbn: "1565924649",
      isbn: null,
      oclc: null,
      openlibrary_work: "OL2784132W",
      openlibrary_edition: "OL6804857M",
      last_loan_date: "2020-09-07T02:46:52Z",
      num_waitlist: "0",
      last_waitlist_date: "2020-08-26T12:48:18Z",
      is_restricted: true,
      is_browseable: true,
      __src__: "core.models.lending.get_availability",
    },
  },
  {
    key: "/works/OL1643770W",
    title: "JavaScript",
    edition_count: 20,
    cover_id: 10737959,
    cover_edition_key: "OL739825M",
    subject: [
      "JavaScript (Computer program language)",
      "Web servers",
      "Object-oriented programming (Computer science)",
      "JavaScript (Computer language)",
      "Mathematics",
      "Programming Languages",
      "COMPUTERS",
      "JavaScript",
      "COMPUTER PROGRAMMING",
      "COMPUTER PROGRAMS",
      "PROGRAMMING LANGUAGES",
      "OBJECT-ORIENTED PROGRAMMING",
      "ALGORITHMS",
      "FILE MAINTENANCE (COMPUTERS)",
      "SOFTWARE TOOLS",
    ],
    ia_collection: [
      "americana",
      "americanuniversity-ol",
      "bostonuniversitylibraries-ol",
      "china",
      "gwulibraries-ol",
      "inlibrary",
      "internetarchivebooks",
      "ithacacollege-ol",
      "kalamazoocollege-ol",
      "librarygenesis",
      "occidentalcollegelibrary-ol",
      "printdisabled",
      "rochester-ol",
      "schroederlibrary-ol",
      "the-claremont-colleges-ol",
      "unb-ol",
      "uni-ol",
      "universityofarizona-ol",
      "wilsoncollege-ol",
    ],
    lendinglibrary: false,
    printdisabled: true,
    lending_edition: "OL739825M",
    lending_identifier: "javascriptdefin000flan",
    authors: [
      { key: "/authors/OL183270A", name: "David Flanagan" },
      { key: "/authors/OL3144731A", name: "James Gu\u00e9rin" },
    ],
    first_publish_year: 1996,
    ia: "javascriptdefin000flan",
    public_scan: false,
    has_fulltext: true,
    availability: {
      status: "borrow_available",
      available_to_browse: true,
      available_to_borrow: false,
      available_to_waitlist: true,
      is_printdisabled: true,
      is_readable: false,
      is_lendable: true,
      is_previewable: true,
      identifier: "javascriptdefin000flan",
      isbn: "9781565922341",
      oclc: null,
      openlibrary_work: "OL1643770W",
      openlibrary_edition: "OL739825M",
      last_loan_date: "2020-07-28T03:30:18Z",
      num_waitlist: "0",
      last_waitlist_date: "2020-02-27T22:51:58Z",
      is_restricted: true,
      is_browseable: true,
      __src__: "core.models.lending.get_availability",
    },
  },
];

export const badGuy = [
  {
    key: "/works/OL858596W",
    type: "work",
    seed: [
      "/books/OL22330689M",
      "/books/OL776216M",
      "/books/OL8645163M",
      "/books/OL499164M",
      "/books/OL8645227M",
      "/books/OL3701162M",
      "/books/OL8645278M",
      "/books/OL8645348M",
      "/works/OL858596W",
      "/subjects/assassins",
      "/subjects/comic_books_strips",
      "/subjects/gangsters",
      "/subjects/good_and_evil",
      "/authors/OL74606A",
    ],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 8,
    edition_key: [
      "OL22330689M",
      "OL776216M",
      "OL8645163M",
      "OL499164M",
      "OL8645227M",
      "OL3701162M",
      "OL8645278M",
      "OL8645348M",
    ],
    publish_date: [
      "1996",
      "June 1, 1999",
      "July 1, 2001",
      "1998",
      "2000",
      "June 1, 2000",
      "1997",
      "March 1, 1998",
    ],
    publish_year: [1996, 1998, 2000, 1997, 2001, 1999],
    first_publish_year: 1996,
    number_of_pages_median: 144,
    lccn: ["98234396", "2003267271", "97177012"],
    publish_place: ["New York, NY", "New York"],
    oclc: ["44697536", "39118892", "37047772"],
    contributor: [
      "Feeny, Carla.",
      "Pugh, Steve.",
      "McCrea, John, artist/creator.",
      "Schubert, Willie.",
      "McCrea, John.",
    ],
    lcc: [
      "PN-6727.00000000.E56 H583 1998",
      "PN-6727.00000000.E56 H58 1997",
      "PN-6728.00000000.H56 E564 2000",
    ],
    ddc: ["741.5973"],
    isbn: [
      "1563894041",
      "9781563896149",
      "9781563894046",
      "1563893142",
      "1563897180",
      "9781563893148",
      "1563896141",
      "1563895099",
      "9781563897184",
      "9781563895098",
    ],
    last_modified_i: 1671575896,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    cover_edition_key: "OL776216M",
    cover_i: 798138,
    publisher: ["DC Comics"],
    language: ["eng"],
    author_key: ["OL74606A"],
    author_name: ["Garth Ennis"],
    subject: ["Assassins", "Comic books, strips", "Gangsters", "Good and evil"],
    id_goodreads: ["95417", "95411", "95407", "110418", "95418"],
    id_librarything: ["576046", "215690", "248186", "136695", "215689"],
    publisher_facet: ["DC Comics"],
    subject_facet: [
      "Assassins",
      "Comic books, strips",
      "Gangsters",
      "Good and evil",
    ],
    _version_: 1759801719977410600,
    lcc_sort: "PN-6727.00000000.E56 H583 1998",
    author_facet: ["OL74606A Garth Ennis"],
    subject_key: [
      "assassins",
      "comic_books_strips",
      "gangsters",
      "good_and_evil",
    ],
    ddc_sort: "741.5973",
  },
  {
    key: "/works/OL21519279W",
    type: "work",
    seed: [
      "/books/OL29182449M",
      "/books/OL29650409M",
      "/works/OL21519279W",
      "/subjects/fiction_suspense",
      "/subjects/fiction_thrillers_general",
      "/subjects/criminals",
      "/subjects/assassins",
      "/subjects/fiction",
      "/subjects/fiction_thrillers_espionage",
      "/subjects/fiction_thrillers_suspense",
      "/authors/OL33236A",
    ],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 2,
    edition_key: ["OL29182449M", "OL29650409M"],
    publish_date: ["2012"],
    publish_year: [2012],
    first_publish_year: 2012,
    number_of_pages_median: 275,
    lccn: ["2014656421"],
    isbn: ["9780345471345", "9780755397372", "0755397371", "0345471342"],
    last_modified_i: 1673788392,
    ebook_count_i: 1,
    ebook_access: "borrowable",
    has_fulltext: true,
    public_scan_b: false,
    ia: ["hitmandamnation0000bens"],
    ia_collection: [
      "hamiltonpubliclibrary-ol",
      "inlibrary",
      "internetarchivebooks",
      "openlibrary-d-ol",
      "printdisabled",
    ],
    ia_collection_s:
      "hamiltonpubliclibrary-ol;inlibrary;internetarchivebooks;openlibrary-d-ol;printdisabled",
    lending_edition_s: "OL29650409M",
    lending_identifier_s: "hitmandamnation0000bens",
    printdisabled_s: "OL29650409M",
    readinglog_count: 2,
    want_to_read_count: 2,
    currently_reading_count: 0,
    already_read_count: 0,
    cover_edition_key: "OL29650409M",
    cover_i: 11645427,
    publisher: ["Random House Publishing Group", "Headline Publishing Group"],
    language: ["eng"],
    author_key: ["OL33236A"],
    author_name: ["Raymond Benson"],
    author_alternative_name: ["Raymond Benson."],
    subject: [
      "Fiction, suspense",
      "Fiction, thrillers, general",
      "Criminals",
      "Assassins",
      "Fiction",
      "Fiction, thrillers, espionage",
      "Fiction, thrillers, suspense",
    ],
    ia_box_id: ["IA1990620"],
    publisher_facet: [
      "Headline Publishing Group",
      "Random House Publishing Group",
    ],
    subject_facet: [
      "Assassins",
      "Criminals",
      "Fiction",
      "Fiction, suspense",
      "Fiction, thrillers, espionage",
      "Fiction, thrillers, general",
      "Fiction, thrillers, suspense",
    ],
    _version_: 1759764772421632000,
    author_facet: ["OL33236A Raymond Benson"],
    subject_key: [
      "assassins",
      "criminals",
      "fiction",
      "fiction_suspense",
      "fiction_thrillers_espionage",
      "fiction_thrillers_general",
      "fiction_thrillers_suspense",
    ],
  },
  {
    key: "/works/OL28033356W",
    type: "work",
    seed: [
      "/books/OL38354973M",
      "/works/OL28033356W",
      "/subjects/fiction_thrillers_suspense",
      "/subjects/fiction_thrillers_general",
      "/authors/OL6789122A",
    ],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 1,
    edition_key: ["OL38354973M"],
    publish_date: ["2012"],
    publish_year: [2012],
    first_publish_year: 2012,
    isbn: ["9780345535856", "0345535855"],
    last_modified_i: 1655546698,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Random House Publishing Group"],
    language: ["eng"],
    author_key: ["OL6789122A"],
    author_name: ["Raymond Benson"],
    subject: ["Fiction, thrillers, suspense", "Fiction, thrillers, general"],
    publisher_facet: ["Random House Publishing Group"],
    subject_facet: [
      "Fiction, thrillers, general",
      "Fiction, thrillers, suspense",
    ],
    _version_: 1759777170896453600,
    author_facet: ["OL6789122A Raymond Benson"],
    subject_key: ["fiction_thrillers_general", "fiction_thrillers_suspense"],
  },
  {
    key: "/works/OL27813060W",
    type: "work",
    seed: ["/books/OL37999585M", "/works/OL27813060W", "/authors/OL10378977A"],
    title: "Fatah-Hamas Ri",
    title_suggest: "Fatah-Hamas Ri",
    title_sort: "Fatah-Hamas Ri",
    edition_count: 1,
    edition_key: ["OL37999585M"],
    publish_date: ["2022"],
    publish_year: [2022],
    first_publish_year: 2022,
    isbn: ["1438487045", "9781438487045"],
    last_modified_i: 1653504903,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["State University of New York Press"],
    language: ["eng"],
    author_key: ["OL10378977A"],
    author_name: ["HITMAN"],
    publisher_facet: ["State University of New York Press"],
    _version_: 1759776776855224300,
    author_facet: ["OL10378977A HITMAN"],
  },
  {
    key: "/works/OL25904765W",
    type: "work",
    seed: [
      "/books/OL34960558M",
      "/books/OL40097151M",
      "/books/OL36008651M",
      "/works/OL25904765W",
      "/subjects/fiction_romance_general",
      "/subjects/fiction_erotica_general",
      "/authors/OL3745392A",
    ],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 3,
    edition_key: ["OL34960558M", "OL40097151M", "OL36008651M"],
    publish_date: ["2020"],
    publish_year: [2020],
    first_publish_year: 2020,
    isbn: [
      "9781953908551",
      "9781953908049",
      "1953908047",
      "9798673051948",
      "1953908551",
    ],
    last_modified_i: 1666183990,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Independently Published", "Sea Port Press LLC"],
    language: ["eng"],
    author_key: ["OL3745392A"],
    author_name: ["Katrina Jackson"],
    subject: ["Fiction, romance, general", "Fiction, erotica, general"],
    publisher_facet: ["Independently Published", "Sea Port Press LLC"],
    subject_facet: ["Fiction, erotica, general", "Fiction, romance, general"],
    _version_: 1759773004537004000,
    author_facet: ["OL3745392A Katrina Jackson"],
    subject_key: ["fiction_erotica_general", "fiction_romance_general"],
  },
  {
    key: "/works/OL30051728W",
    type: "work",
    seed: ["/books/OL41309374M", "/works/OL30051728W", "/authors/OL11066006A"],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 1,
    edition_key: ["OL41309374M"],
    publish_date: ["2019"],
    publish_year: [2019],
    first_publish_year: 2019,
    isbn: ["9781797727288", "1797727281"],
    last_modified_i: 1669317174,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Independently Published"],
    language: ["eng"],
    author_key: ["OL11066006A"],
    author_name: ["Theodore Valley"],
    publisher_facet: ["Independently Published"],
    _version_: 1759781398155100200,
    author_facet: ["OL11066006A Theodore Valley"],
  },
  {
    key: "/works/OL28732883W",
    type: "work",
    seed: ["/books/OL39433060M", "/works/OL28732883W", "/authors/OL7282115A"],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 1,
    edition_key: ["OL39433060M"],
    publish_date: ["2020"],
    publish_year: [2020],
    first_publish_year: 2020,
    isbn: ["9798674158899"],
    last_modified_i: 1660867195,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Independently Published"],
    language: ["eng"],
    author_key: ["OL7282115A"],
    author_name: ["Sean McKenzie"],
    publisher_facet: ["Independently Published"],
    _version_: 1759778415611740200,
    author_facet: ["OL7282115A Sean McKenzie"],
  },
  {
    key: "/works/OL29449805W",
    type: "work",
    seed: ["/books/OL40543420M", "/works/OL29449805W", "/authors/OL10877952A"],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 1,
    edition_key: ["OL40543420M"],
    publish_date: ["2018"],
    publish_year: [2018],
    first_publish_year: 2018,
    isbn: ["9781980522072", "1980522073"],
    last_modified_i: 1668877703,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Independently Published"],
    language: ["eng"],
    author_key: ["OL10877952A"],
    author_name: ["Harvey Madison"],
    publisher_facet: ["Independently Published"],
    _version_: 1759780040059388000,
    author_facet: ["OL10877952A Harvey Madison"],
  },
  {
    key: "/works/OL587828W",
    type: "work",
    seed: [
      "/books/OL10686121M",
      "/works/OL587828W",
      "/subjects/murder_for_hire",
      "/subjects/assassins",
      "/subjects/fiction",
      "/subjects/fiction_science_fiction_general",
      "/authors/OL43146A",
    ],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    subtitle: "Enemy Within (Hitman)",
    edition_count: 1,
    edition_key: ["OL10686121M"],
    publish_date: ["August 28, 2007"],
    publish_year: [2007],
    first_publish_year: 2007,
    number_of_pages_median: 320,
    oclc: ["149573908"],
    isbn: ["9780345471321", "0345471326"],
    last_modified_i: 1670216699,
    ebook_count_i: 1,
    ebook_access: "printdisabled",
    has_fulltext: true,
    public_scan_b: false,
    ia: ["isbn_9780345471321"],
    ia_collection: ["china", "internetarchivebooks", "printdisabled"],
    ia_collection_s: "china;internetarchivebooks;printdisabled",
    printdisabled_s: "OL10686121M",
    readinglog_count: 10,
    want_to_read_count: 8,
    currently_reading_count: 1,
    already_read_count: 1,
    cover_edition_key: "OL10686121M",
    cover_i: 2405302,
    publisher: ["Del Rey"],
    language: ["eng"],
    author_key: ["OL43146A"],
    author_name: ["William C. Dietz"],
    subject: [
      "Murder for hire",
      "Assassins",
      "Fiction",
      "Fiction, science fiction, general",
    ],
    id_goodreads: ["1302181"],
    id_librarything: ["3827350"],
    ia_box_id: ["IA1157617"],
    publisher_facet: ["Del Rey"],
    subject_facet: [
      "Assassins",
      "Fiction",
      "Fiction, science fiction, general",
      "Murder for hire",
    ],
    _version_: 1759795825690542000,
    author_facet: ["OL43146A William C. Dietz"],
    subject_key: [
      "assassins",
      "fiction",
      "fiction_science_fiction_general",
      "murder_for_hire",
    ],
  },
  {
    key: "/works/OL673651W",
    type: "work",
    seed: [
      "/books/OL425813M",
      "/works/OL673651W",
      "/subjects/city_and_town_life",
      "/subjects/fiction",
      "/subjects/fiction_thrillers_suspense",
      "/subjects/london_(england)_fiction",
      "/subjects/place:london_(england)",
      "/authors/OL52682A",
    ],
    title: "O, hitman, my hitman!",
    title_suggest: "O, hitman, my hitman!",
    title_sort: "O, hitman, my hitman!",
    edition_count: 1,
    edition_key: ["OL425813M"],
    publish_date: ["1997"],
    publish_year: [1997],
    first_publish_year: 1997,
    number_of_pages_median: 164,
    lccn: ["98131672"],
    publish_place: ["Ilfracombe, Devon"],
    oclc: ["38959166"],
    lcc: ["PR-6052.00000000.E648 O2 1997", "PR-6052.00000000.E648O2 1997"],
    ddc: ["823.914"],
    isbn: ["0722330650", "9780722330654"],
    last_modified_i: 1635828793,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    cover_edition_key: "OL425813M",
    cover_i: 1359282,
    publisher: ["A.H. Stockwell"],
    language: ["eng"],
    author_key: ["OL52682A"],
    author_name: ["Eleanor Berry"],
    place: ["London (England)"],
    subject: [
      "City and town life",
      "Fiction",
      "Fiction, thrillers, suspense",
      "London (england), fiction",
    ],
    id_goodreads: ["2435671"],
    publisher_facet: ["A.H. Stockwell"],
    place_key: ["london_(england)"],
    subject_facet: [
      "City and town life",
      "Fiction",
      "Fiction, thrillers, suspense",
      "London (england), fiction",
    ],
    _version_: 1759797980008808400,
    place_facet: ["London (England)"],
    lcc_sort: "PR-6052.00000000.E648 O2 1997",
    author_facet: ["OL52682A Eleanor Berry"],
    subject_key: [
      "city_and_town_life",
      "fiction",
      "fiction_thrillers_suspense",
      "london_(england)_fiction",
    ],
    ddc_sort: "823.914",
  },
  {
    key: "/works/OL29880745W",
    type: "work",
    seed: ["/books/OL41086044M", "/works/OL29880745W", "/authors/OL3477150A"],
    title: "Hitman's Pet",
    title_suggest: "Hitman's Pet",
    title_sort: "Hitman's Pet",
    edition_count: 1,
    edition_key: ["OL41086044M"],
    publish_date: ["2018"],
    publish_year: [2018],
    first_publish_year: 2018,
    isbn: ["1983054895", "9781983054891"],
    last_modified_i: 1669186649,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Independently Published"],
    language: ["eng"],
    author_key: ["OL3477150A"],
    author_name: ["Heather West"],
    publisher_facet: ["Independently Published"],
    _version_: 1759781080827691000,
    author_facet: ["OL3477150A Heather West"],
  },
  {
    key: "/works/OL7918433W",
    type: "work",
    seed: [
      "/books/OL9864313M",
      "/books/OL30013840M",
      "/books/OL9270322M",
      "/books/OL7315665M",
      "/works/OL7918433W",
      "/subjects/boxers_(sports)",
      "/subjects/biography",
      "/subjects/boxers_(sports)",
      "/authors/OL2644480A",
    ],
    title: "The Hitman",
    title_suggest: "The Hitman",
    title_sort: "The Hitman",
    edition_count: 4,
    edition_key: ["OL9864313M", "OL30013840M", "OL9270322M", "OL7315665M"],
    publish_date: ["September 21, 2006", "2008", "April 22, 2008"],
    publish_year: [2006, 2008],
    first_publish_year: 2006,
    number_of_pages_median: 352,
    oclc: ["70671457"],
    lcc: ["GV-1132.00000000"],
    isbn: [
      "0091910862",
      "9780091910853",
      "0091910854",
      "9780091910860",
      "0091930839",
      "9780091930837",
    ],
    last_modified_i: 1677591283,
    ebook_count_i: 2,
    ebook_access: "borrowable",
    has_fulltext: true,
    public_scan_b: false,
    ia: ["hitmanmystory0000hatt_q5x6", "hitmanmystory0000hatt"],
    ia_collection: [
      "inlibrary",
      "internetarchivebooks",
      "openlibrary-d-ol",
      "printdisabled",
    ],
    ia_collection_s:
      "inlibrary;internetarchivebooks;openlibrary-d-ol;printdisabled",
    lending_edition_s: "OL9864313M",
    lending_identifier_s: "hitmanmystory0000hatt_q5x6",
    printdisabled_s: "OL9864313M;OL7315665M",
    readinglog_count: 0,
    want_to_read_count: 0,
    currently_reading_count: 0,
    already_read_count: 0,
    cover_edition_key: "OL9864313M",
    cover_i: 1093095,
    publisher: ["Ebury Publishing", "Ebury Press"],
    language: ["eng"],
    author_key: ["OL2644480A"],
    author_name: ["Ricky Hatton"],
    subject: ["Boxers (Sports)", "Biography", "Boxers (sports)"],
    id_goodreads: ["1467787", "2578700"],
    id_librarything: ["4772682", "2747948"],
    ia_box_id: ["IA1822813", "IA40241901"],
    publisher_facet: ["Ebury Press", "Ebury Publishing"],
    subject_facet: ["Biography", "Boxers (Sports)", "Boxers (sports)"],
    _version_: 1759877297258627000,
    lcc_sort: "GV-1132.00000000",
    author_facet: ["OL2644480A Ricky Hatton"],
    subject_key: ["biography", "boxers_(sports)"],
  },
  {
    key: "/works/OL5741169W",
    type: "work",
    seed: [
      "/books/OL8975081M",
      "/books/OL16250635M",
      "/works/OL5741169W",
      "/subjects/large_type_books",
      "/subjects/fiction_psychological",
      "/subjects/murder_for_hire",
      "/subjects/fiction",
      "/subjects/mate_selection",
      "/subjects/meurtre_à_forfait",
      "/subjects/romans_nouvelles",
      "/subjects/choix_du_conjoint",
      "/authors/OL1395811A",
    ],
    title: "The hitman diaries",
    title_suggest: "The hitman diaries",
    title_sort: "The hitman diaries",
    edition_count: 2,
    edition_key: ["OL8975081M", "OL16250635M"],
    publish_date: ["August 2003", "2004"],
    publish_year: [2004, 2003],
    first_publish_year: 2003,
    number_of_pages_median: 335,
    lccn: ["20115465"],
    publish_place: ["Leicester"],
    oclc: ["59372588"],
    lcc: ["PR-6111.00000000.I54 H5 2003", "PR-6061.00000000"],
    isbn: ["1852428287", "9781852428280", "1845057147", "9781845057145"],
    last_modified_i: 1675970849,
    ebook_count_i: 2,
    ebook_access: "borrowable",
    has_fulltext: true,
    public_scan_b: false,
    ia: ["hitmandiaries0000king_y9c8", "hitmandiaries0000king"],
    ia_collection: ["inlibrary", "internetarchivebooks", "printdisabled"],
    ia_collection_s: "inlibrary;internetarchivebooks;printdisabled",
    lending_edition_s: "OL8975081M",
    lending_identifier_s: "hitmandiaries0000king_y9c8",
    printdisabled_s: "OL8975081M;OL16250635M",
    readinglog_count: 2,
    want_to_read_count: 2,
    currently_reading_count: 0,
    already_read_count: 0,
    cover_edition_key: "OL8975081M",
    cover_i: 900731,
    first_sentence: ["You know, it's a lonely business being single."],
    publisher: ["Howes", "Serpent's Tail"],
    language: ["eng"],
    author_key: ["OL1395811A"],
    author_name: ["Danny King"],
    subject: [
      "Large type books",
      "Fiction, psychological",
      "Murder for hire",
      "Fiction",
      "Mate selection",
      "Meurtre à forfait",
      "Romans, nouvelles",
      "Choix du conjoint",
    ],
    id_goodreads: ["110419"],
    id_librarything: ["7926956"],
    ia_box_id: ["IA40603521", "IA1938003"],
    publisher_facet: ["Howes", "Serpent's Tail"],
    subject_facet: [
      "Choix du conjoint",
      "Fiction",
      "Fiction, psychological",
      "Large type books",
      "Mate selection",
      "Meurtre à forfait",
      "Murder for hire",
      "Romans, nouvelles",
    ],
    _version_: 1759795356573368300,
    lcc_sort: "PR-6111.00000000.I54 H5 2003",
    author_facet: ["OL1395811A Danny King"],
    subject_key: [
      "choix_du_conjoint",
      "fiction",
      "fiction_psychological",
      "large_type_books",
      "mate_selection",
      "meurtre_à_forfait",
      "murder_for_hire",
      "romans_nouvelles",
    ],
  },
  {
    key: "/works/OL29754342W",
    type: "work",
    seed: ["/books/OL40926230M", "/works/OL29754342W", "/authors/OL3477150A"],
    title: "Hitman's Baby",
    title_suggest: "Hitman's Baby",
    title_sort: "Hitman's Baby",
    edition_count: 1,
    edition_key: ["OL40926230M"],
    publish_date: ["2018"],
    publish_year: [2018],
    first_publish_year: 2018,
    isbn: ["1980351279", "9781980351276"],
    last_modified_i: 1669092776,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Independently Published"],
    language: ["eng"],
    author_key: ["OL3477150A"],
    author_name: ["Heather West"],
    publisher_facet: ["Independently Published"],
    _version_: 1759780838368608300,
    author_facet: ["OL3477150A Heather West"],
  },
  {
    key: "/works/OL27950693W",
    type: "work",
    seed: [
      "/books/OL38201475M",
      "/works/OL27950693W",
      "/authors/OL9788924A",
      "/authors/OL2543141A",
    ],
    title: "Satyr : Hitman",
    title_suggest: "Satyr : Hitman",
    title_sort: "Satyr : Hitman",
    edition_count: 1,
    edition_key: ["OL38201475M"],
    publish_date: ["2021"],
    publish_year: [2021],
    first_publish_year: 2021,
    isbn: ["9798473397499"],
    last_modified_i: 1653658676,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Independently Published"],
    language: ["eng"],
    author_key: ["OL9788924A", "OL2543141A"],
    author_name: ["Robert Wealleans", "R. Harris"],
    publisher_facet: ["Independently Published"],
    _version_: 1759777029093326800,
    author_facet: ["OL2543141A R. Harris", "OL9788924A Robert Wealleans"],
  },
  {
    key: "/works/OL16561591W",
    type: "work",
    seed: [
      "/books/OL25250032M",
      "/books/OL28537885M",
      "/works/OL16561591W",
      "/subjects/man-woman_relationships",
      "/subjects/revenge",
      "/subjects/fiction",
      "/subjects/triangles_(interpersonal_relations)",
      "/subjects/assassins",
      "/subjects/african_americans",
      "/subjects/fiction_african_american_urban",
      "/subjects/criminals_fiction",
      "/subjects/journalists_fiction",
      "/subjects/african_americans_fiction",
      "/subjects/fiction_urban",
      "/subjects/fiction_african_american_&_black_urban_&_street_lit",
      "/subjects/fiction_urban_&_street_lit",
      "/authors/OL3096735A",
    ],
    title: "The hitman's woman",
    title_suggest: "The hitman's woman",
    title_sort: "The hitman's woman",
    edition_count: 2,
    edition_key: ["OL25250032M", "OL28537885M"],
    publish_date: ["2011", "2015"],
    publish_year: [2011, 2015],
    first_publish_year: 2011,
    number_of_pages_median: 446,
    lccn: ["2011276409"],
    publish_place: ["Deer Park, NY", "East Rutherford, NJ"],
    oclc: ["711051181"],
    lcc: [
      "PS-3601.00000000.R387 H58 2011",
      "PS-3601.00000000.R387",
      "PS-3610.00000000.O6617",
    ],
    ddc: ["813.6"],
    isbn: ["9781601624628", "1601626371", "9781601626370", "160162462X"],
    last_modified_i: 1670666171,
    ebook_count_i: 1,
    ebook_access: "borrowable",
    has_fulltext: true,
    public_scan_b: false,
    ia: ["hitmanswoman00arch"],
    ia_collection: [
      "china",
      "inlibrary",
      "internetarchivebooks",
      "printdisabled",
    ],
    ia_collection_s: "china;inlibrary;internetarchivebooks;printdisabled",
    lending_edition_s: "OL25250032M",
    lending_identifier_s: "hitmanswoman00arch",
    printdisabled_s: "OL25250032M",
    readinglog_count: 1,
    want_to_read_count: 1,
    currently_reading_count: 0,
    already_read_count: 0,
    cover_edition_key: "OL25250032M",
    cover_i: 10040775,
    publisher: [
      "Distributed by Kensington Pub.",
      "Penguin Random House",
      "Urban Books",
    ],
    language: ["eng"],
    author_key: ["OL3096735A"],
    author_name: ["Devon Vaughn Archer"],
    subject: [
      "Man-woman relationships",
      "Revenge",
      "Fiction",
      "Triangles (Interpersonal relations)",
      "Assassins",
      "African Americans",
      "Fiction, african american, urban",
      "Criminals, fiction",
      "Journalists, fiction",
      "African americans, fiction",
      "Fiction, urban",
      "Fiction, african american & black, urban & street lit",
      "Fiction, urban & street lit",
    ],
    id_amazon: [""],
    ia_box_id: ["IA1111303"],
    publisher_facet: [
      "Distributed by Kensington Pub.",
      "Penguin Random House",
      "Urban Books",
    ],
    subject_facet: [
      "African Americans",
      "African americans, fiction",
      "Assassins",
      "Criminals, fiction",
      "Fiction",
      "Fiction, african american & black, urban & street lit",
      "Fiction, african american, urban",
      "Fiction, urban",
      "Fiction, urban & street lit",
      "Journalists, fiction",
      "Man-woman relationships",
      "Revenge",
      "Triangles (Interpersonal relations)",
    ],
    _version_: 1759753176511152000,
    lcc_sort: "PS-3601.00000000.R387 H58 2011",
    author_facet: ["OL3096735A Devon Vaughn Archer"],
    subject_key: [
      "african_americans",
      "african_americans_fiction",
      "assassins",
      "criminals_fiction",
      "fiction",
      "fiction_african_american__black_urban__street_lit",
      "fiction_african_american_urban",
      "fiction_urban",
      "fiction_urban__street_lit",
      "journalists_fiction",
      "man-woman_relationships",
      "revenge",
      "triangles_(interpersonal_relations)",
    ],
    ddc_sort: "813.6",
  },
  {
    key: "/works/OL30068410W",
    type: "work",
    seed: ["/books/OL41331600M", "/works/OL30068410W", "/authors/OL10893772A"],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 1,
    edition_key: ["OL41331600M"],
    publish_date: ["2019"],
    publish_year: [2019],
    first_publish_year: 2019,
    isbn: ["9781688051515", "1688051511"],
    last_modified_i: 1669331441,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Independently Published"],
    language: ["eng"],
    author_key: ["OL10893772A"],
    author_name: ["William EVANS"],
    publisher_facet: ["Independently Published"],
    _version_: 1759781371648147500,
    author_facet: ["OL10893772A William EVANS"],
  },
  {
    key: "/works/OL29019712W",
    type: "work",
    seed: ["/books/OL39903092M", "/works/OL29019712W", "/authors/OL10162724A"],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 1,
    edition_key: ["OL39903092M"],
    publish_date: ["2013"],
    publish_year: [2013],
    first_publish_year: 2013,
    isbn: ["9781304462435", "1304462439"],
    last_modified_i: 1666035156,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Lulu Press, Inc."],
    language: ["eng"],
    author_key: ["OL10162724A"],
    author_name: ["Peprah Boasiako"],
    publisher_facet: ["Lulu Press, Inc."],
    _version_: 1759779182959657000,
    author_facet: ["OL10162724A Peprah Boasiako"],
  },
  {
    key: "/works/OL8495203W",
    type: "work",
    seed: [
      "/books/OL8018017M",
      "/works/OL8495203W",
      "/subjects/electronic_games",
      "/authors/OL2838355A",
    ],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 1,
    edition_key: ["OL8018017M"],
    publish_date: ["December 12, 2000"],
    publish_year: [2000],
    first_publish_year: 2000,
    number_of_pages_median: 176,
    isbn: ["0761535098", "9780761535096"],
    last_modified_i: 1631701829,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    cover_edition_key: "OL8018017M",
    cover_i: 510292,
    publisher: ["Prima Games"],
    language: ["eng"],
    author_key: ["OL2838355A"],
    author_name: ["Prima"],
    subject: ["Electronic games"],
    id_goodreads: ["1902749"],
    publisher_facet: ["Prima Games"],
    subject_facet: ["Electronic games"],
    _version_: 1759801518970634200,
    author_facet: ["OL2838355A Prima"],
    subject_key: ["electronic_games"],
  },
  {
    key: "/works/OL30214504W",
    type: "work",
    seed: [
      "/books/OL41531817M",
      "/books/OL42137945M",
      "/works/OL30214504W",
      "/authors/OL10766717A",
    ],
    title: "Hitman",
    title_suggest: "Hitman",
    title_sort: "Hitman",
    edition_count: 2,
    edition_key: ["OL41531817M", "OL42137945M"],
    publish_date: ["2019"],
    publish_year: [2019],
    first_publish_year: 2019,
    isbn: ["1074922964", "1793921261", "9781074922962", "9781793921260"],
    last_modified_i: 1669793196,
    ebook_count_i: 0,
    ebook_access: "no_ebook",
    has_fulltext: false,
    public_scan_b: false,
    publisher: ["Independently Published"],
    language: ["eng"],
    author_key: ["OL10766717A"],
    author_name: ["Clive Harman"],
    publisher_facet: ["Independently Published"],
    _version_: 1759781715107119000,
    author_facet: ["OL10766717A Clive Harman"],
  },
];

export const newTin = {
  key: "/works/OL21519279W",
  type: "work",
  seed: [
    "/books/OL29182449M",
    "/books/OL29650409M",
    "/works/OL21519279W",
    "/subjects/fiction_suspense",
    "/subjects/fiction_thrillers_general",
    "/subjects/criminals",
    "/subjects/assassins",
    "/subjects/fiction",
    "/subjects/fiction_thrillers_espionage",
    "/subjects/fiction_thrillers_suspense",
    "/authors/OL33236A",
  ],
  title: "Hitman",
  title_suggest: "Hitman",
  title_sort: "Hitman",
  edition_count: 2,
  edition_key: ["OL29182449M", "OL29650409M"],
  publish_date: ["2012"],
  publish_year: [2012],
  first_publish_year: 2012,
  number_of_pages_median: 275,
  lccn: ["2014656421"],
  isbn: ["9780345471345", "9780755397372", "0755397371", "0345471342"],
  last_modified_i: 1673788392,
  ebook_count_i: 1,
  ebook_access: "borrowable",
  has_fulltext: true,
  public_scan_b: false,
  ia: ["hitmandamnation0000bens"],
  ia_collection: [
    "hamiltonpubliclibrary-ol",
    "inlibrary",
    "internetarchivebooks",
    "openlibrary-d-ol",
    "printdisabled",
  ],
  ia_collection_s:
    "hamiltonpubliclibrary-ol;inlibrary;internetarchivebooks;openlibrary-d-ol;printdisabled",
  lending_edition_s: "OL29650409M",
  lending_identifier_s: "hitmandamnation0000bens",
  printdisabled_s: "OL29650409M",
  readinglog_count: 2,
  want_to_read_count: 2,
  currently_reading_count: 0,
  already_read_count: 0,
  cover_edition_key: "OL29650409M",
  cover_i: 11645427,
  publisher: ["Random House Publishing Group", "Headline Publishing Group"],
  language: ["eng"],
  author_key: ["OL33236A"],
  author_name: ["Raymond Benson"],
  author_alternative_name: ["Raymond Benson."],
  subject: [
    "Fiction, suspense",
    "Fiction, thrillers, general",
    "Criminals",
    "Assassins",
    "Fiction",
    "Fiction, thrillers, espionage",
    "Fiction, thrillers, suspense",
  ],
  ia_box_id: ["IA1990620"],
  publisher_facet: [
    "Headline Publishing Group",
    "Random House Publishing Group",
  ],
  subject_facet: [
    "Assassins",
    "Criminals",
    "Fiction",
    "Fiction, suspense",
    "Fiction, thrillers, espionage",
    "Fiction, thrillers, general",
    "Fiction, thrillers, suspense",
  ],
  _version_: 1759764772421632000,
  author_facet: ["OL33236A Raymond Benson"],
  subject_key: [
    "assassins",
    "criminals",
    "fiction",
    "fiction_suspense",
    "fiction_thrillers_espionage",
    "fiction_thrillers_general",
    "fiction_thrillers_suspense",
  ],
};
